<?php
/**
 * @file
 * shanti_kmaps_vocabularies.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function shanti_kmaps_vocabularies_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-kmaps_places-field_sameas_kmapid'
  $field_instances['taxonomy_term-kmaps_places-field_sameas_kmapid'] = array(
    'bundle' => 'kmaps_places',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_sameas_kmapid',
    'label' => 'KMap ID',
    'required' => FALSE,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-kmaps_subjects-field_sameas_kmapid'
  $field_instances['taxonomy_term-kmaps_subjects-field_sameas_kmapid'] = array(
    'bundle' => 'kmaps_subjects',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_sameas_kmapid',
    'label' => 'KMap ID',
    'required' => 1,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('KMap ID');

  return $field_instances;
}
